### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by flydsc** [sfischer13/python-arpa#1]
Hi,
Thanks for creating this toolkit, seems like satisfied all my needs.
However, when I was finishing pip install and trying to import the package, i got this error, any help would be appreciated.

``` python
Python 2.7.10 (default, Aug 22 2015, 20:33:39)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import arpa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/arpa/__init__.py", line 37, in <module>
    from .arpa import dump, dumpf, dumps, load, loadf, loads
  File "/Library/Python/2.7/site-packages/arpa/arpa.py", line 3, in <module>
    from .models.simple import ARPAModelSimple
  File "/Library/Python/2.7/site-packages/arpa/models/simple.py", line 3, in <module>
    from .base import ARPAModel
  File "/Library/Python/2.7/site-packages/arpa/models/base.py", line 8
    class ARPAModel(metaclass=ABCMeta):
                             ^
SyntaxError: invalid syntax
```

**Comment by sfischer13** [comment]
Unfortunately, Python 2.7 is not supported.

**Comment by josepvalls** [comment]
What is the reasoning? Would you be open to a contribution to support both or should I fork it?

**Comment by sfischer13** [comment]
Hey @josepvalls, I might have underestimated the need for Python 2.7 support. By hindsight, there have been several requests. Sorry!

I created a new branch for Python 2.7 development ([python2.7](https://github.com/sfischer13/python-arpa/tree/python2.7)) and I also created a separate package on PyPI ([arpa27](https://pypi.org/project/arpa27/)).

I has been quite a while for me, so I must first reactivate my Python 2.7 knowledge.

**Comment by sfischer13** [comment]
Hey @josepvalls and @flydsc, this took *far* too long, but now there is Python 2.7 support.
The package is available on PyPI: [arpa-backport](https://pypi.org/project/arpa-backport/).

Installation:
```sh
$ pip install --user -U arpa-backport
```
Usage:
```python
import arpa_backport as arpa
models = arpa.loadf("foo.arpa")
```
