### ISSUE TITLE
Weird versioning breaking pipenv

### ISSUE THREAD

**Issue by madhavajay** [sfischer13/python-arpa#3]
Pipfile:
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true

[packages]
arpa = "*"

$ pipenv install 
Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
Could not find a version that matches arpa
Tried: 0.1.0a1, 0.1.0a1, 0.1.0a2, 0.1.0a2, 0.1.0a3, 0.1.0a4, 0.1.0a4, 0.1.0a5, 0.1.0a5, 0.1.0a6, 0.1.0a6, 0.1.0b1, 0.1.0b1

Where as:
$ pip install arpa
No problems.

**Comment by sfischer13** [comment]
[This hint](https://github.com/pypa/pipenv/blob/master/docs/diagnose.rst#-your-dependencies-could-not-be-resolved) should solve your problem until the package is declared stable.

**Comment by madhavajay** [comment]
Oh I didn't realise it doesnt install pre-releases by default. Thanks! :)
